---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    job: "helmfile"
spec:
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
    - key: "profile"
      operator: "Equal"
      value: "highmem"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: agentpool
            operator: In
            values:
            - highmemlinux
  containers:
  - args:
    - "99d"
    command:
    - "sleep"
    env:
    - name: "HOME"
      value: "/home/jenkins"
    image: "olblak/helmfile:506a6f"
    imagePullPolicy: "IfNotPresent"
    name: "helmfile"
    resources:
      limits:
        memory: "512Mi"
        cpu: "400m"
      requests:
        memory: "512Mi"
        cpu: "400m"
    securityContext:
      privileged: false
    tty: true
  - args:
    - "99d"
    command:
    - "sleep"
    env:
    - name: "HOME"
      value: "/home/jenkins"
    image: "olblak/updatecli:v0.0.6"
    imagePullPolicy: "Always"
    name: "updatecli"
    resources:
      limits:
        memory: "512Mi"
        cpu: "400m"
      requests:
        memory: "512Mi"
        cpu: "400m"
    securityContext:
      privileged: false
    tty: true
  restartPolicy: "Never"
  serviceAccount: "cluster-admin"
