nexus:
    secret:
        data:
            ldap_password: ENC[AES256_GCM,data:S+imEFkMJnIE+YDG,iv:fGqRJnN65ef2+7gtuxRxmneDOnI8z6tzBNO73jb8PPA=,tag:wIhN8KgGdde0oZ1YvQbfYw==,type:str]
            admin_password: ENC[AES256_GCM,data:GpAAz4FJfmbYeFUCMsVthv2pAhzNlHjRG/uO5w==,iv:2K+YqqARdCaxurr35CZWYkpr28c2Mzi3Zq6KCXAocDI=,tag:Mm+5p88ELb0xUcTdF7MN6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-05-31T13:52:09Z'
    mac: ENC[AES256_GCM,data:5hJU+XO4c7yF7eZgoactedgYnfPhSIPBAyBv6FHO2BLzEscNqi2JODO4ceVfCBPhSKDvf9bftIThFf7aFFe6AX10849iNZ1es5ax2vr4gAMFXcHDDRc8Rrb0yG6rTWDQZpjdMKvdJcTa/ZykK/YVIOUPCuzsCMlo3jE5hMKA8k0=,iv:+E0e+VBAsdCmtu0W8/5IKrJwidL1JTo3UmeQwTVZvEI=,tag:PxLfhh8kcp7N0RtrIHxuhw==,type:str]
    pgp:
    -   created_at: '2019-05-31T13:36:42Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAWNgf+6+xtIGT5UOjS7hzYbAiJ677NO/E++znyHQ4jbos
            Id3zIX5zcoNYofHFpLzTxn8NRcjCSfZ9A5x1/qmo2fxddF4IjXGKBR10OZCdWaUg
            URVaDugITn36FtDlZUMxYg1s02uolAuNf0GIRCQIfk3RYJJobytu4pHmbZM1cU0q
            JMEMc0jEqV7sXIDbZkGiAcA9hUUQOSgva64Yqyfy3NJFezNf3oZWYVbpCBXpNBg5
            KMJJeHQEdvX1GFhHo4AUqaZIZdL0ub7o1XHs1y6NkDdvVDSw84qdOZ+cKsDJOXhh
            xDlOHkcGRnwABgUHF21D5TRb+6sxsQV3hnvD+QoIh7s4ItkMD9WC9qxC2nzDJThD
            fLS561eufGImjXvXgsvq8JHb+hye/7U7nc9f+bEkZyzRiL7pBgaDjVfNc9juT7bq
            cQLRYG0ldkKCZAXzNgiH5kPEEldXXEXPaElXzE2BpqzIXNZ9CurswdXmXUcEayFd
            HCcvcYlOqEO1ihNYaSnS/DucO8NaxT145LSb6qxacPM49ySB8coGpCqWsHAN2uO4
            QQ2PEhl0CWrAKrzLsvPhuMFURMk0BHjRgJ66OHjh7kX8+7F/qjfv9Y+oEQRxmlGn
            a+5XMZWFD65mtswDhk6EYL8IQt2SFW5S/PzWjo6MlCvjFYXgWFWEZUpud36viU7S
            4AHkST/AwWnQ7Ej2L3yEEBYXX+F/DeCg4JfhmAngveK/vFcq4K3lun75SHA6D7SB
            UfuMftyVuJiEhTbNmH1tnR4rEF4kEy7geeQE9NVZHgMspzME8l8Sd0np4u6d1Tnh
            62YA
            =uPfn
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.2.0
