confluence:
    username: ENC[AES256_GCM,data:KKb+2F0KWvwiu7xGEvP7NC6nDyt9mF5XWg==,iv:WIGBoFSccVMNUk4EZLjtrE40MO+i4S80mY8vXkP8RBg=,tag:4Yg4uu7FDRxgY9XQY/DfFw==,type:str]
    password: ENC[AES256_GCM,data:B7tPgUdHT8wIGEozkxHh+K05hmw=,iv:Oyz0y2l3BpBJJ3ljQulAjvQLW/Xj3hhBjW7DJp/kG0w=,tag:eTj5MxkR05Agg9kANMZc+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-10-25T07:42:50Z'
        enc: oA2G7ouQNl0ZaPJi735gwspQkB2V0dvN0e0BElO46PYORBxqhp_V4gVRI702aADm-mwkSwe5KXydja7ByixNPtKjo5NrZAjXDuwWWiiqfVEfUhHSeNWlzITrEM459K4Pf-onlLAG-hAaXXCUjnT20_8bojGzz3stFHysPAhhRPBQfWMlkokqMBu6nBkoX7W_AnomEBjfQT03Ne4TDka0AGEaIuTq-kxU0XHEW6ySrQODZ8kF4x77nJ34pA_Q5lPp_G1y8iNTQZ6u_V6LmZ_z2IcLy11MjDE4XFbVtrhBo8rHvX8lIlb6gWkWVzT5JinyLNP_wpJiIxclS8UFBjOx3hbP-mMBvX4u9TjW6_4bsCs7Xh97ZXH2jrUKS2pN3J5-CVajH1i6_2hQbXp57SAW8Dk5VffpUgw9KVgzr9zXp-qoWsZa945iGbNqKtp-IwCzfiqeTkEtSnwUiGNjRt9dK3dDleY27IjfPvrN9Xwz5V4A4TH260vtG_69lSvBX86-TVccRVQoeE3Mc9jWAUrCnNJIlNj52N4n5aLKBveV208DZ8fZGTOuHqZtJFHy40N95_fvHPiHK1y5MkmkhfazLzukIJ0VgP71K3k8vhq6UaVINaCfuRqZzvYdUpFUGhZrAEaQeMw5xdmHHqRFEWSvCXoHIi9xnH5uLnlaP75K9cU
    lastmodified: '2019-10-25T07:50:46Z'
    mac: ENC[AES256_GCM,data:vXxST/8B3CCdbp3yvQtXOUHLU+EOOtdzvL7tdsBHFzFH7vvqtMjzGKczd7tZueubo7qFJyg6LSQFGgvf22m12IMs7t8VlpqodCnDERWbi3EVafpUY1A/iUp+iIPtbyjy6UylPlippm0VrLNhlVSCDfgUu362f4uRfBr3JB6EPgc=,iv:KsA8jEcDF0VILd0n2B4RMANv4U87/lVApISrt+NjdFI=,tag:ReXr72vZmFQhDGRXLA+Nww==,type:str]
    pgp:
    -   created_at: '2019-10-25T07:42:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7pRwZh7mkwAAQ/+IaOAAlT2vVzFvpx7w/HIs4AJLBHRcpm8cbBnlpYxfFC0
            Ggq7CzLr5aVEit4XwiCz/DllzLL0e869s+o9BH2tv60HhpcUF/eLNG4lTU0qzXG6
            nh8W+e7Gwdem8HE3nZ+oe+PK7WA/KBXZyIHIJRbbvv2qMqnfYZ9b44t8lQH6cTAC
            lQxHZDsVNSaHeQdvtHKtXt3qCvn52v7wSaxWFS8kBAtuP/4c8gZ/StFryER4bMLr
            XNUxljRqJoOy4hwfzi0mPO9tQsK8/HFPXyTHNOBltMeyehP2HKiMafmq1KNK5JmI
            tTs8ihpmmeksbd5Y2kBHZaKPHvt5AzG3sbvuKKHeg4Swuuqr0nh4d79KM/TzwYUm
            54UpsuH6S0Kwc4+LMYkReNBvRs3SqaYhDctfJTF80yoKrA85/q11Pcx7TEmIHwS3
            U80CyTM8hdAFGdDB0GR7gXsqSxHx8BxDJ6XghexSNIBXxUBpdCEbDk11h04BNvNY
            2BGcxemOjIx7Z9t2dyURaCvZ3IURddAE8we3mx55tsC4uoYAJW/lyPuVRCy1ClTm
            uq0gSWE4hf0U6ja88AKgepI0+SJHwpKldd1Rz0LvZs77i6sH9n9TfTttjw5SWqiK
            pPkaIx+uNGBAxgWGba9R4sQYMKTo2w/PuXNixIvxc26AHgVkFmy0zegHXV0O19LS
            UQGrMW3iQltrLqrJnnLd9OJfbmnp5wdpvJU0Yy6P4Aq6IhVUtmbgiS3d5nzXYSbs
            oEbrYniFhaw1eeW+ymUoXe8MOE5K81DU5dz8T6tnBVI3oQ==
            =/xzq
            -----END PGP MESSAGE-----
        fp: 88FABF5F307FB5870B6AD2E8A266F2D3F9D60C45
    -   created_at: '2019-10-25T07:42:50Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAqQsY8Gm7A3NSuQdF3OZLFOUywcYKnEOarU/PGCgy4YkM
            vMyAm9plPAGDuFU7VuEuyIznsRScOZuWjJdn6Fb6COWtpVFTaewG4SNOLh0smCSt
            VKHtcovMdvNoCabmESfnhs2tpJDK1lk8cUOHeix48B6AVSTQLV+945UE3wL7aQlZ
            rIzE5h8wQVWPuFfjOBnD9KUey8eK34J3C0RO2ygAbqU5sPL/F4NZOI8j4eBOZ5uQ
            JpY1w4crqAvQDjwSmvdjAnWXMuN11Sy9kMXS98J6KHNPrsdghM4DtWdqaBVqobJI
            LuAixGT1nS3u+J+xKP7r68ZG7FBOgV0sY5gvO5ThLsF3ujE+Hl9LLJZBZVeoWEhL
            u8mTpHABBH169zvXUOBG3Q30QIhgvbv1PH64ObV1pbPRjOimnl7+NsN4cOOUxr4J
            Euh+u34aeJzSMG0HnFJS9qwo5StlRf/fCcnaZmLsRnuU/fs3yH9RasJMCerIoF/4
            AqFP+yz932qmH3vnOqb1+ox6vJkTO0fv9yKn7eHOUcKT0fY2F+m9oiOa9RVSLIad
            EJZX+/d3O1FElZWb12y9XwjjIJdYAkPY0bRU+5yc+d/nRw9RSj+otmGZWMQ/QVB5
            SSkKOJX92op0itQaojfzTYPB5V0N1fm8yUQIrvSSvaBLyb9izgXl3KOh++C7PLvS
            4AHkrR66oAVOfFRXZ5szQ36+MeHOUODV4OnhBzPggeJSG6Xq4ALlJVdyAO+2jj2s
            bIgB2y46rgbC/nK5QDfx8Jc8DK0rB/rgwuTKMf76qCKQi0+wMAZas2Rb4rsscHTh
            9RUA
            =zAHb
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.4.0
