config:
    clientID: ENC[AES256_GCM,data:ERxxmbs=,iv:gDkY5DsSdGT4TKfKw5BHwxBIUTQRt5Z7MU48aBrhERU=,tag:wwiGstBVDLgtu/oScqThhg==,type:str]
    clientSecret: ENC[AES256_GCM,data:CbjoKLRWk8lRYVaCieS0T18atLyuD03VqPVtQJW01Ys=,iv:JukES/EUlAYq+Wv6tDIn6bziYx6Ts/BbrV44O60r++o=,tag:oAithac9uZG+C9mD7qGE8g==,type:str]
    cookieSecret: ENC[AES256_GCM,data:kZUdvGrSbql/fvmhqDrxeMWEPVXo1C4SFgimPyju0op3CZTmva6EzRKnhkI=,iv:T4YFRdTpXtzNI6wt4SIEpFMPPVf79jecc5/cqLSjZcA=,tag:id/1Rat5ZrHmFBuTF3vrxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-11-07T08:53:30Z'
        enc: Hoyl6-pEUjr2xR6ADTp2ruyeeUnqQIQWib52cG3gWadZW5gFxipP5e6m8gyUuZSU85hIJK5YCIPQ0-f2wX-pKwmxeWk7ugcjnHZDgzqa8j5puW5sGPl7y_DNNsouYcuETkO5h38W3E52UeFYzDmvSbCVrBm7lc7ZTHEd-qqKHikYye5ix2imeWGANggpbjxKvcL6sX_srZkTN7O7kn87emhEml_0qSXPm4rHTL4ue6PmXZ4sqgxDWfXq5Nk-HwfBJrBuZ3BGaV5UIqetPg6GPLkNByAi_7LmYkmZ8YcXS6l2hpcY5sECkgAJTrsH231Elo55hxxLFKLA2KyNIDUkQx3l-CE_0-LCxbIvZUTTahCli6QGn9mxg3OIFKsfs5JhLzdwOxb0_lFySB-lcxxJjrKJGZasvIuTBDoqpL-S4-Cp_R6jLS2pkB3TM_N3PfpN14OnNsEKBDlZn3lZ02KudF9dI45f2j5rwvI0WCouxesoNiep3FA-6TjVzO5I48abvHvNsHZBMuyUHKLwMYNQy2e9PgxNho5Xkn281NzkEQcj0lPRSvURexVHlA7x0h9PbHAY5gswR_2e_HshukV9enfrkC-JdUIURTr7-4yfikgX5M6TfqXsoUnVCkUkpeBrxkIwUkQ98LX6dwWcRxQ8dxiVHqCPtvWVT7VawE0LI4U
    lastmodified: '2019-11-07T08:55:38Z'
    mac: ENC[AES256_GCM,data:FSv6QQzkzNCrSRxmNc1O4Ul91jVW0gRjYG6CEOA6K1YU9t3LE0SLEaboze6AouqkKiMBFPNn9gQwV1s/CyH4h623vfAFM8gh5DSmzEWCzsrGOcLFaoYkaSQE8iN3roDtrooDbPH4RZLaIsEeG5H0z9DWrHtl9gZ8hi8wa5znfxo=,iv:JaOJSRrunJ832+PJEl1fkOSlIJMYKj4w0mGJJVER0H8=,tag:tUykVN4ruE51HxOn7ic2ZA==,type:str]
    pgp:
    -   created_at: '2019-11-07T08:53:30Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAs9EyukePR2GmIjU7pTpyofOhm+4Z3ZeNcfMmbh+4zwaz
            d+WRdAM3vv74oI9XrVWjPfFTxKsHGYvj4LApEWznFqbXBTyiipkz9m/w2HZSQCad
            mgwp7XfmefQFztotPUh9DEepmVdfTr3UGT2RhayH7RCQR5LdazTdhhrlg/bVan3G
            gzHTbkeZbAkt32ci7neM1IUxYsSDAXAVg6Pw6vs0pY87WQ1Z3e9Uljyj7Q/PT1UO
            9al2OTTon8sLfxnDouCvHmwKd8idQRMPBs5vXt1ePH/bN9q6rXkN2yk+QHw8JFNb
            Ujsczywu/3nTl3nxkyQ9eipOKmpQRbT5gPix7f8zTgOrCA77NM8nba3FtWJ3NWUC
            NiQt3MNG8qyHzTIobaDlntafX+VfsIGrzr54ZfMbOikiumvoVl+zDZ2tBq/MzlDn
            8WvJytJ5fGg9pTjhDst/OH2q4oTAVQvI3j1GbHnYjealkpwNXux2raM5d680V4UB
            sIORPOmHS+wFeXXQ3E50ABsDYFPYxDcsArGBM3RS6zC+PjIHoJk4TiokgUjxXDou
            AZuRcbsk152qpmJzl7rMv3orX7pU1gboD/QLRDBZ04YRDWnxKX5BzwKtyQKn/4va
            dHn5rTVaA4EI1q8LplSbaSeD6fR+Lf89b93/FTqvvbmaarhT0OSoyDOahAcoILPS
            4AHkp0+7PNUVj2JV4H0CabS3geGm5OAB4FPh8BvgceLDMD824Pvl2Qg6a/rMfbpz
            cLCX3BC2uEsogEDXp/FjdPRmmXlvwHbgT+Ti0chF27qRiBWGIdDEGruE4nvr8Afh
            A4MA
            =76We
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.4.0
