# https://github.com/helm/charts/tree/master/stable/grafana
ingress:
  enabled: true
  hosts: 
    - grafana.jenkins.io
  annotations:
    "certmanager.k8s.io/cluster-issuer": "letsencrypt-prod"
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
  tls:
    - hosts:
        - grafana.jenkins.io
      secretName: grafana-cert
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 50

#https://grafana.com/docs/administration/provisioning/#custom-settings-per-datasource
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.loki:3100
      jsonData:
        maxLines: 1000
      editable: false
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.prometheus
      jsonData:
        maxLines: 1000
      editable: false

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
    level: info
  grafana_net:
    url: https://grafana.jenkins.io
  auth.ldap:
    enabled: true
    allow_sign_up: true
    config_file: /etc/grafana/ldap.toml
