datadog:
    apiKey: ENC[AES256_GCM,data:t/wG,iv:H/IgYOosDcYUeR8IBJJVgy7CXK3ESsK0sMJj7l5VBeY=,tag:+fOY3imWJGAcOKILw+jiDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-03-28T16:49:47Z'
    mac: ENC[AES256_GCM,data:dSXS004tIvGH8t9cUA+haVKNUKpEapEimI+nhBxOgZ+Sba371kWr3F0mdB+mDks3DpHuPuvTCvcqRSkdiwtDOvvFmJjhu7WErUC5oAqxwqJqz7X+YkuctSUzFUKErrXZ+XtS91CAJxmF4Yzcr5A9VhP7XlRzL75UlkrIuIIPcCM=,iv:jrUvxjrZeqNEuWdZjUyk5lTq0fwF+iwW2taGAlGY/5I=,tag:sT8gha6ehpulBCJgmTzYRQ==,type:str]
    pgp:
    -   created_at: '2019-03-28T16:49:47Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAYgnjiuvvJEtBH7n6oQJYkXpK6S4Iu/jkR+L8eU+7jT1v
            jBEZzLvC8nBINQX7ZdIy42eZhRmaCxBeZ/K8Cx8n0rjXKPJSeFsDsGRWu7CX0ybj
            IRJpZnlOFcs0H2DLnwiy96seZapL1EIQdZi/h9MB7Oi9tzlekHXNha8Y+NX/EaJu
            vEx48dwfJkyZWmwhYNj4mgXJOPjIKU3JuPjriJQpDfVhEB/VA2rkAp6K7RW7AfIn
            IIvnswz/cuXCgh8Ix4KNGZCigFCFY9X2N1V+PyOlmQX3t7LEk2nbTQExXTP/LVff
            hH6SJlyOf+LaNhXCKBp0t3SzQUO/T2X5LKwbjZZJGOiBk1Pin0wy2Tfa6nbQei4C
            4LbLIFi8cHTQJENxfiPxvi69jqsdhzOuT19zkZfnLRNW5f54aOAKHaoLvVU/F55z
            xvVAgSJ2XBJJChEs0vI0/83mNfiCerK84IrofitNcfFGkugPqzPxJ1NArWTSAaua
            ytyZG/qJ9gqX7JdPXfnU+MhrLBT/KY6g+Jfsn2yHAlDGcQBpFGArrQadWltOuIUd
            daMDH6QCe1xC3bmcujk7AJ0LN4lXQky75DfpIs3EjA3HvM2lj+jp2q6N6tuGALLo
            Dq6uQQr0tb+CDbqUt1Ks/3GnqOyzOBvTqcLVoRAYRzdJ6ISyC6Xj3W3IWz1nmY7S
            4AHkGznpacqhk3EIWjakfX/DC+F+qeCR4Obh3F7ga+JsI2kd4E/lpozk7/8/FdWP
            i2KJeA/6E7kFwfZYsnw0+Ff3Hd7QZe3gX+TLergDOHEK2ScY6UbTBxgH4pesu//h
            yhMA
            =vH+R
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.2.0
