datadog:
    apiKey: ENC[AES256_GCM,data:HdFEHNRNWZwJuK/EcU9bVrRQVcr/z8fVu6jrPUP/UDg=,iv:/UjWFZmUXZvt2XYmMwSB3WFz2V5M+R5rMMgcnT+GCEg=,tag:1vtgOSVtzY3HMmuQWucVBQ==,type:str]
    appKey: ENC[AES256_GCM,data:MoC6kvDsHYIWIH0+K3PqrLHLRA7pVEmd4VsRGUpBDi/gtXI/afzSUQ==,iv:ENzrliTA1U+A7MvMDGzCjNOBN2t5aJT3HlknN2ioaO0=,tag:sZwiW4xiWpUUMH8/yh8ZgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-06-14T12:58:59Z'
        enc: Qu37TN2Hvv_OnH-Mbu3JxYg8d_9zvb47-jFnGvk7z0LUQsj4Wy8Lal-EKWaB0USZr9Owood4VkpAjz99SpD5QsffKmKV6Wihne9yFEUK8-9wTMuYy_CvEgfVcNMd0FyZ9m5uLg6N5e7aikKSFXbKK5WIC0KGILilP-xXXAsazlfokGVFTvhrWEfvghAE49F6tJerEzegr48Yqkor2Jb0oqo4aykxEGuPkn0NnGfxCRftoPJAm45EuSLEYr2AIBUpEtbaJE5pHYX60bC6J5dxtr-f5DvhMRyIiUvU5TerfKZApU1pGndUBDJp4fkc43Ln7lAeVd3cgWZqGvT2anLOu6Zc_9NOXRP1xpCUyELcsbGzUoxBolPedDf3jp2mqT0UnwSMAeSTdbQOHVWthF2cKyZrb_MWiEqSRNPbMMaedYmtUWwzZ75dHPctfjQMiSkAsTtdW_-fsVRblMnvar36lxdYvTJ-ycNqtEKTw76U76SkCkyjqOUiiGMJ4-pJ9UweSZZMZMhsjaqGfJPmxYiM66Nxe_4tMGCvlqqMxqsr1C6CGecVs9SIOv5v9-_-supoKu-OQSqiwmmPSlkG2nsQR4Eii5XSzTLurX92vqWziv7saBaYOi7uG0r5YAnfdpga7DtxGaiMy-SgNV5mGiB5V2r_yLVfEzfWbw_W4dqW32Y
    lastmodified: '2019-06-14T12:59:00Z'
    mac: ENC[AES256_GCM,data:O30wzoicfTvNJnexgILSDphX8RfJpPUDzp31Ww42l0wd1WBvqTeyblezrk7NjRKky2U6H2k/n6ddJg2Pymvk5JcS15/T+fq+uN97V72Iq2sfQueS/zsAldzS4UzayzISlGrK2G7s3Wcq24drxhui+52eqOdRL7q88JjL0Stvu3I=,iv:FniUFdM/eNPc/o6zv7VL4a5uzl9T2pryeLF7LEoXTAQ=,tag:kxCJ54VlSCeJLRSkiGRDzw==,type:str]
    pgp:
    -   created_at: '2019-04-02T15:17:58Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAACy5JOtLSaXwEDmFRs9lEMzz14hWtJl49I3Gj5KlyT4GE
            ThYnYaoTSQ17O5ymuxGYL7K5tqVqTZoFkyBrNC/Q3UnTjZhVV7r8Sg1U0l9/NdSm
            urN4jhbUQvf3HLkJnTYu3W4XMkHlGIYr0WlUrayveA6LwwBiujyosaUliYiEY3S2
            FL6q3EMmrZ/WshtHN4+pABz7E0VsmIJzMo9+Ta7cwbdI6f/QEFMBirYjpNkcpF+a
            UwnUi1bR33HlzW4Z/dZ4o+gAVeX6MTmkI5fc+eQaXXazTOEl672u/NGKTDGkxbAy
            +8vQ1hyRJH1AEo+dh/UeZ7FcrJk+anqDahlXKv92jG4G9EnTi4eCUMy+HNat2j3V
            G/EQ3f5EdPhaNdZnJjhaVFRSTPFrR4oNTmchrC1EVd0M3mng+XAf3VOeQqykKO4d
            ajCMbNbovgbVDT0CctTgAUqSubNYsHq6U/t5DxqD0UcQeUhiRN0cQLvk89muIjr8
            TDFIZkKdFfteh8H6Rm/G83eAHhR3kF1+NvUpfGIIaL7IrY4qpsIa9KDU5lQPGo3i
            Lshm6y8tJNabcHJ+cO1UtKLpbJw0hBPntnPFLCOaYZBxq7DVlmDyea4xWj9BkNwx
            FyqGQcbdQigiP/SPXU5mV3x3y4ihxPxvn7p9wwZ8oSybC340TPMHl9+JVCLM2tTS
            4AHkTZGfD7W4pzubwn6yZByVdOGHVeAh4FThBdXgA+LEoetQ4DrlPaT0O49bsLN2
            F1rP3mN4kVoWqpImkUT/M93bKGmoeJvg9OStWDX6KcwAO0VRJgUjQ9pQ4m8ZnErh
            zGwA
            =GkEt
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.2.0
