datadog:
    apiKey: ENC[AES256_GCM,data:VplI07PsksyvfSQLVCvkFdpMFR8mkGz06DQbN0ZWOr8=,iv:/UjWFZmUXZvt2XYmMwSB3WFz2V5M+R5rMMgcnT+GCEg=,tag:fTmAhBSyQuryj7EmHJAV1A==,type:str]
    appKey: ENC[AES256_GCM,data:BVX2z1VICOI6PyXSxWZEsrZE/lIXdcju7+ZNn+SPdmxQ/Yyh4GC5dw==,iv:ENzrliTA1U+A7MvMDGzCjNOBN2t5aJT3HlknN2ioaO0=,tag:Jtwplq97ZTP7uJudby/WCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-04-02T15:31:04Z'
    mac: ENC[AES256_GCM,data:bmejx5f7BYHQ/6hzuARoSiLNypW6p7ITV+wOwOKiIz/0YGVbLppp1zxdw837kuApzH9tZ0BKIJJ1wgBExQS4fHkzUn+sd+08wmSHh1ZrHQ0fZ7eKcRq7IYgL7DML5lM41Y92DWTbCeB1gzC2/eXQAiN7NHnkrv+Hj0/uQtpEEhY=,iv:C5uNse2/VBMDo8zeiL20OwozwtmFlXyL+tM6lhuoqL0=,tag:ddms0uaHbXn1RhQf/ZXIwQ==,type:str]
    pgp:
    -   created_at: '2019-04-02T15:17:58Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAcRfvGApd8rqwWxVdJyBVhIZ2U3M9sEExr8cn4JXhVe0D
            gfJh3CpRBbh7+d6UHY72+DgQv1jaGfX/oewENg2lGcKAnGQFpJJuZ/bsyXJsdsyN
            AoL9FoKOniffsK90dptLMIAkonk+F1YUzJZpMzo0sMaQja3DnY8S/SzAiGsYRX7l
            EwtHQwfDtYWQSgXTOIBqi2od64doXS71GhctZDhiDYuy4xxQCXpIFUx2hGvyvZAQ
            iii1uVJATWMkEJsb9iGBMsDMpDEMSVMMhoM0XmVBdqz6/0H+7UygCYklEAmsnmuw
            EoxIE408qPQfs2kHdQHjihqHIjSJ2le1GAWNtINVQXKq3sQxFqZ040E6VYHfOEz5
            DBl4l7O1EdYKpMEeOvxda52ci4hdpWL+1iO64h6foB3IpnnfvdkeNBCwdhpJxHS+
            KyEuXuCCQGU0IE4nhhKj3Pjqkb182UaMmt8QukYOxV99tTjGYykRaLjpCp9l8kG/
            aRf11IIcThn3/gPQTTL7oGmVzocOXtiVVsNx0IEdMin2ok/ova2XkcR98Mg+3e65
            qxXzVa0d+0LDYo8McLDBpHAPkX8RqlyTQnET6aO/31/J7PZ1mCqcrc671hV1RLPL
            7/sT257tctB6RHe49VMu8yr/tfX44K8kApiotrFqsH/w98Z1cP6Vo4Og6XdaxwTS
            4AHkJSmd2J2LXpCIoy6t2sjlcuGPq+BB4O7hYjTgqeLU69o44CrlDSi7omRybXHM
            DGu6t8gRaUeMexqixzs0BEfSWRP4ELfguuRSh3FZ9LWoCs7K+gOosJeZ4rpCLlzh
            fSUA
            =0ce/
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.2.0
