corePackages:
    binary:
        storageAccountName: ENC[AES256_GCM,data:G2XphTKc6QTjVN3SHN39Tu52pwM=,iv:4iXX/N5nn4elu2H0UlKzLHaU73CDNsfBgG0dnAzvmvc=,tag:F6yFoSanEnMTnR/OA8/QZQ==,type:str]
        storageAccountKey: ENC[AES256_GCM,data:m+/vtU8GMHbAfAaX7ykSYa4rhUBJe68FukFg8DCp52QTqtrEHvb2uq1KdWLTp+EjWN1VARs1JUb6gpfPQGIbdyRGaNAeuiYNUkGdav09UeZo9lIEY34Q5n2q2ci4p9CWjSGEIZ6YDX5eTX3qk79bR5hZ26lLEPyb,iv:NXoMh4noCRggaZGPkIHpI4MTE94G1ViJ9BLidRHKqIc=,tag:kSZo4LAy/0b9nob7i7kFEA==,type:str]
        shareName: ENC[AES256_GCM,data:n6AXOeKAUYk29Dqyldm9qJTzwOI=,iv:8kuw+e46Og9tGCS33SMTxCUb2cNJ92lszJFS5qXPlV8=,tag:Pi6AWF6LubbwfGUqJyG1rg==,type:str]
    website:
        storageAccountName: ENC[AES256_GCM,data:XMqHY5685I8mJK4ppB4on0zYT/Q=,iv:doRAFO/+RZvCyEXz33b0s35xq7PLSIvkKtmSZv07FRk=,tag:0ehIUJ2ju5LktJ2mlzJs2w==,type:str]
        storageAccountKey: ENC[AES256_GCM,data:aU70mRObsTZ264ljoQnR7t8TW3pUro7fZBtXBM87aytL1nqpz0dhEWZXAuxa11wwxbRzFief8e/B52Rlxdgnd/LgI0C2Ga4O4m556O3/54IERg8a9XoXcPQOeSJpi9KMID3NrnyXmA1WgxjzsygAzF2bnJQl3iqF,iv:5MzySr3N7VYrqyG2BeQQv2NZzQeEIpyup9ZF/w2w7UE=,tag:bTQrWKwkYCvBtmXU9O3kCQ==,type:str]
        shareName: ENC[AES256_GCM,data:T7lTCyqjkdQHV1OigE9zw+deSQ5T,iv:eFSjJuL1H9F8EgWqOFW+tsXZCnnErgWXQahl+QmiiBQ=,tag:c0ip63otW2+ucEuzV2Izzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-10-18T08:55:01Z'
        enc: BVcoA8j_g8Rf0-m7J-Q1W7lTrLU-kZzjsQxpfm-IddLFgxMtCZcG0JbstDz4o4W2zDP-nBM_moZcRpEu2yCJBi3I8v6nlN25K8yMm8rf1u-Z2N-NccUCXHBcR00gi1L0h-4ozkvpdyTHea_wm2thsnVyUI1yPJjOiNVvOMYqcWOboGZFcoEuIaLuCvD4Jcvz3sDV65Zu8YTgUgOSM6Vqihkyd6pnYHnfWLyLeAtCYYlz7fIKDIMUxTzKZXSJ_rFIyYsVtX412L7aZToKE3V4eVb5fAYY-YknYCZ2iH3SkCMYy-QsPqZBy8F_0aSTh9u3kkXPLsg_WuIG4Mwkw8v8xRy4tSv-M-Jz3MBrNYKnn33zqUW5dI1072O9s-1RMHXQWOCY4cVclmeuiXedVUm6EeQ3fuMLXCUAKOTJrXg9p2LCmD178OiCIT8OslWMpwfz-af_-mbGlXXy0CtW4upCnfSIiCsJY9O4INvOGJgxsupSR6MUqeI2Lrt2quDI0SkGXdftzrFCrCId2oeDraOf58HP-7trcw7wiithFBsxHQ0Fv6IPW-Nq_VVHkZQoz55M1A7-41oEfc46zCNyOcaPjY-4j2h3iHsxtBLkp52ga1oTIvcdiyPAIgjKXzk9696dZVgzm1i51wTyEImSBlij9ideNs1tOf0gZRArNQtUrJU
    lastmodified: '2019-10-18T10:59:05Z'
    mac: ENC[AES256_GCM,data:5w/7/h4Xmrt/0AvhDH1VGVREWFAJUt1l3T+nuX3Qi2410rpzQTm4aFTH4lpave9wxt/QkeyJqyO9wO0xwJgDni2fEIJjkqO64TXeTotJKBsKEYTbBlWoStjhUbUZ+Ltjs/YWj3sojyoiWU1T7mXYM3LoS2S5fBHPXobzLf3PrWY=,iv:ty7dkjf5m2OGZkzDV7dqIUWzxVnX6sL0J3GyT6of2GA=,tag:pB0atyqJTUobO5jUE+zGyg==,type:str]
    pgp:
    -   created_at: '2019-10-18T08:55:01Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAc9oWwl9GHV7nT3/8YkWZzekeQ13VnGnWTYAKY2rivqBl
            Vz7wTL42cWQ04Ud3vJcpBwAat5DjppCnjiX/iKHd5OD4cMTadqqwR2yCYTQsn6+d
            4AVhpgN/gBTarhjtAFNpOddHty2vFYhBZjfUrzh5DtJJDLk5+Oo+S0WkC2uYsVm1
            /aU9xnMHa62Omz5d6VnL5cu1vzLTqVOVNypYAEEUMC/la40nsiFznOe+9ZRuWBIy
            xkYTQyu296ShVWcJZDwFmYWSxE1C7rBca/ZjUdcoZrtwlxP9Qfzo5t13++nFThvy
            Sh7k09ww0F6NLmWdZge8hBcjao3qlRS33bRduVwcRjaalpe2u/sbkXWJEX19j3jR
            upQLQZyJU1olp4kNqBNrTGxXZ+Zu8d+/4sPhP2dKk7HsNN5LjJfqiDzC12SK5uTw
            mdC37hviUJg56j57c3XKPrLnvitHN8VHUXLgJiy2v1cl7HF3Exxqzy7jwcSoMpoO
            vwoqoQKJOOZHsAlZKf9uuGjwXDwEEE1C2aH06jsWLEAVnnf4V+mB3VIJ1hL3ZAbb
            rJyse3pqTf6tVNtXLnGTE7DbF00JzWn1CrKoU3EEK+C5aaGdqFfTwCj/pOKezcxo
            guROmM0ShwRp2iByXoGLVHxiCW9FHA2Uopc8Gj5paI7MZAhqEc+ZLBG/o8T0DZ7S
            4AHkRRzXWPjLqq1lFr5VJFjMAuEoIuBC4IHhhJbgl+L/I9He4D7lGu1xdvawElaJ
            qggRHGoOun6WrntaTwmsYN5/+eZisWjgyOSTzeWQ3nKTSGiJF1vloc2U4sxL1lTh
            E6oA
            =3Y2i
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.3.1
