ingress:
  enabled: true
  annotations: 
    "certmanager.k8s.io/cluster-issuer": "letsencrypt-prod"
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
  hosts:
    - host: release.pkg.jenkins.io
      paths:
        - "/"
  tls:
    - secretName: releasepkg-tls
      hosts:
        - release.pkg.jenkins.io
