ldap_manager_password: ENC[AES256_GCM,data:VDtbqfricio=,iv:+KxCKGTAtz408t5+zek4KkDEp556OGFim4URv0GCSv4=,tag:Di1OKEpLjbudCViXdG2PRQ==,type:str]
ldap_manager_dn: ENC[AES256_GCM,data:Lca3WogK+BihUaOdiI1bBPDY+0yunR5OpKBqSR8=,iv:h7mIUNJ6vX8EIsBB7S61M8qMcQQuMpVy/VeX86nIJv4=,tag:buWblhESW/d+uMAWpH40pw==,type:str]
ldap_server: ENC[AES256_GCM,data:WY2fJ6Wu5LaPdFMvmSAU,iv:8XIO9K1z824906IoAQJbr6rXC9/W+kAFJNn/EuyIAM0=,tag:+6vNgApW+CfUcYZn05RkPw==,type:str]
ldap_root_dn: ENC[AES256_GCM,data:EyBm5xXlrgWPfWhjuxKKDTmSTxQ=,iv:mCwqUZ4H+bgLJNRy/1/h4PZf1lpEXpRTgsKoJd0aud8=,tag:6dZJIJl7VckV4FCBn6UXBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-06-14T12:58:45Z'
        enc: IHDc5tcWCI4zlzmUS8_bSmWoTICp6AEYQyv-To1K0uSiAW0RQiWyYpDpYKEyGRgSGqECngd0_zwm3plsW12z5a2JGkz23NrwDglEJhcrkKZ1WIoK8Lt1tOsfTvcVOreMbF0nGEKoUOq_PgwcTa0RPv5uE97vbyOAbV--qJl-jFO83tb0dmytSm-VOGMWwb7do5mSbINQhVMwWnuphjMTbnvuyUr_8ga_uSYTuFxlU4_NW8YaTcpJkvzslCrvZLS6W-TyT6BYTQ61-dfr-pVTaxOXpwYzS9L_Ho12safVToBezU6jMby-WIarzq-_0VuCGAK7r_r5W2uf-d0LzShJsyhKXH416ZTw4KckbY4MdAIVndaCB87euDUB6AAW2zQwd2jpM47pAlJSSGsQqG3kWbjs9g4OtHtR7NKusmt2Tm-8zzuQ2cdORH9NDGyL2vwzrR_6Q6WIvkOwEbfWV8doM5cMzoh95P4SyK3KDvlZRBpdFXCXkHO2WNjeA-B5vnWBvrsYvMmkMajfz4mN9D0RBYPE4qoDyW-vtlFuoSvXOwaYlYHlgJ4QZAaLk0agIapdtRYCxX-0vw5-8nCuSB-lWQZaCsxY-VDk_a6O8DFqiwpnW7xmcqsMsIavssdcbn76Kq53JDDkvA02izZRCho7gQ0z2HYoe5SRMrbGI0boTHE
    lastmodified: '2019-06-25T09:25:01Z'
    mac: ENC[AES256_GCM,data:GvJfl957YpXNbpDMm5ScWXnRpLwpXjZhlWjIS773J0ymlt0rQYsoEfDfx0tzMRVbQM1WMYnvkrLyytrsCZlxUQ09423IEtOq9N3AShuiKro+STqxVOa6a16keWnQZECFR/y/QwQVQ/tUU+46miCMJoZFJd8E0Hs+NvnZXaZeDd0=,iv:6yKW3eR7GZuqjrTcKrIsTcq5XmvkVqGY7opxJi+FbJo=,tag:RVjmQAy2nkgLBSep78xjXA==,type:str]
    pgp:
    -   created_at: '2018-11-16T19:05:37Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAkAnzroZH0cdgXFu4t5ulbB0Mu1zv4403iRqIIUOrltmd
            GLYo7PE7B0BTMoTAcQ5C8SMOb56v+gcDgGgzbY9XOgkB6dt5e3oG/GNPetsev2Q0
            YAb4/fqSh9SVH1by/JPYGhL90vPX6iCn1ZhwesuXiEmaHxnit9lJV9QUj9mS6P4p
            XUvcIIxJjkzH6lvQ4X2pRpNAms86iJC9Tx0y/W/MPjfTNbR0bonROlVVBYl2RY78
            cwS0mvkEd909I0cm9r2/KAIw/QayLJHuDzBNm48rUx1UugmNUNOVp0iR3ZSB/4E+
            /QP+9Y5W8nZ1QXxbaGWpRk0hDYCEPj1eKDA0KwTKtzMIJgFsiCNhglBaLsx6oioE
            rtavbdVnHOPPPmXhbrPyzAGtVcQvE5LhTdAjeSYdkSC0cFJgC9h0kp9xObxJ1iEX
            VvOr/QtAi3QptcT0aXvBWAOjX17WVhrXYFvQ9ZicK0uJaEUODt2fjUoS57DdtlBu
            woy0S7ruQaypV3wlngks+lUxNA0ZXuO1mS9cCzwgyF2mR03Toin89A7hk8JCsvlv
            q1wPpWtnl1FPQ8WR7irg1CxICnVucflpq+aR1OqmEqJ3geKm+NHFDMgz/6qthtXo
            spKmb02ijoXf1glywE1GYhkOqF13uMqNVBKFdPZlBmI+vANo7EvSnIc1u+BN9VfS
            4AHkHCV2mo6T/qNpmFn0XlYLseE2pOD84IzhhsPgqOKQi10w4APlyL6gifWw42yq
            CPPnnK5l6Lg5UJQxKyZZ+zLLa/SH3n7gwOSl3Nzt4UzdQ+MjZOte34Uv4j11aDbh
            zRMA
            =hzV5
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.3.1
