config:
    issuer: ENC[AES256_GCM,data:rPN5MXOUNtx+ig9qTUeEyd6gpUPTTNK0gk2k1H1V,iv:oB5skzILcnBHwlowva7qbMJLk84QhsDLqc1/7svfIZU=,tag:mloTKEqSoIOZ+1Ae4+Em2g==,type:str]
    frontend:
        logoURL: ENC[AES256_GCM,data:C3Gi/vTYawsktDk3Wzo0P/I44q+jnjfRxoxJxHqqW2tcpZ9daRwTuuaBO/Hb14Z2r3HAgLA=,iv:vO0jjqYgzuOWNw5U8pryVFxsmshuPsoH9EGXD2ZPuDk=,tag:EXWk6kH8qAF+mH114gOCiw==,type:str]
    oauth2:
        skipApprovalScreen: ENC[AES256_GCM,data:lGBQng==,iv:AoJy0/wU3Bg6tVVUVBu35v8FejB4c7f+6jz62h2CX+M=,tag:8lxxH2O3P5JpEDjeDWKSPg==,type:bool]
    connectors:
    -   type: ENC[AES256_GCM,data:1dTJx+Wx,iv:SHrnQF4aIIJomU/ok43kXlpUudd0Z7hhjPD0CtDRcgo=,tag:vkBusY3VZKNY6JOLhY/t8g==,type:str]
        #ENC[AES256_GCM,data:PsJ4xQ9wcVJN2WMTHfnWy8dNYOCDejuxDzZ7WclTyua4,iv:zxn01p94AU9gnfFF/Fyp3h/uJkXC7zbMBDYf2CYd14g=,tag:XP66cw4Sqfr6qbftW5KBOQ==,type:comment]
        id: ENC[AES256_GCM,data:ylIliHeq,iv:26iEL+aDAIXKAEhl8xnPC+e+RxhcXNw9FhFrFSWLRf4=,tag:Fv0Debg7foQRZjQuzu1kXw==,type:str]
        #ENC[AES256_GCM,data:XR3r1NM7viEShqrfe/J/+ZnZPlZKXXaOsT3WbXrdzJOiU+Q=,iv:OhqmRJdTB2o4znp3WVaD/k9I5IOZlkay1WSRItvzY68=,tag:H8jTI5aHNZj+rYAmKnEwqA==,type:comment]
        name: ENC[AES256_GCM,data:iyR2JRl3,iv:BP3EQN+17w7ZHfe/rYE6u5CT+IUdQspD0GBzp5vlHiY=,tag:jFPm0X1EiD/AwEBO/Ewu4A==,type:str]
        #ENC[AES256_GCM,data:/J0/EQSErDZ6ZZLd8tnkjzDi6IcrCkMIBdmvQwfsu9fwcVxTXwqjLlM1jeDgMPI+Uo4ynKYPbaWco9/NxePDGXtqMA==,iv:CKkeWYBYNRsBcasmApZfZk5VGtMdbHZ8f2SRMjA5WfI=,tag:QLicbmL62zYU+WGvztFqyQ==,type:comment]
        config:
            clientID: ENC[AES256_GCM,data:HkdvfYBupPVxhlfJDde/EJ1v9rQ=,iv:jESVft+KE4l3KZcJeVHc0j5uozz3nsRcjdmaJmwUT2c=,tag:rFSH8hwVJk1BnN6QBIa7+A==,type:str]
            clientSecret: ENC[AES256_GCM,data:I5f1gEtnSbp8eyrl8zq8IMziz5ImFuQXoPQL+9bAP2wo9xXCHnM/Og==,iv:evcNBg9lt+AexdqQKf+LovyXkCtOKAxQeuUbMSQ/3go=,tag:7niJiBRz6oylJNnSZrrDlA==,type:str]
            redirectURI: ENC[AES256_GCM,data:rcgFuql1Uw0MsOdmsNWs0n4fqp7I+Q+rDJAIdCeH/3dxa2UK/cvy,iv:n1bAWlzWiA+aiIPpwC0XRGN/QprzfAeyLGt9h7ZDZiM=,tag:7V27iyA9fUOX4nnRNwsnuQ==,type:str]
            #ENC[AES256_GCM,data:TaEcCZhK0qUdQP4ej++ZFSVa5T5+PO2/1vqbSo8=,iv:FfwXd2S2FK5El7wQ80ZMlFRWd51CB6ljCdLz38SmVpw=,tag:P3OqgujR7e5J4Pm3YjQABA==,type:comment]
            orgs:
            -   name: ENC[AES256_GCM,data:pvaegwtZXIpNYUEK0A==,iv:Vs1DjkQofAJLwKzbfEOQMe5A8KUMUTxQdDfzvXl8I7E=,tag:iZJdBqro12IjBadmoSUCQw==,type:str]
                #ENC[AES256_GCM,data:sSaZMcTfppSAvKmJzNo84XPqHAhNmFkPjb3XOjzt+CuG+l12PQfv3kTVPZiRoTsxwX6a5mwlWW+gFRHBw9aA5BP+,iv:6j5IjChpFA/Lb2Iexfo5h/fQajsEg9ZeIohsbzo5GzM=,tag:dHdmp85ZXUi62dVGyaErPg==,type:comment]
                teams:
                - ENC[AES256_GCM,data:pIqevA==,iv:eAR9rm901i9aoFvtgst+KPxQNbukGDsgOpMPSlJNqnI=,tag:ZHVf3wX2Zq/qcf4zLl6e4g==,type:str]
                - ENC[AES256_GCM,data:9+gqCyjez1PdT1WOwS1EvxQmML/0A+7Wxfr+Co/AOCISuG1F7dS2EvdrRxcn3kFFFIPwQ9924ed5hssLqr2S4DqAhA6JCw==,iv:jzSwu4WTO8XbK4QxA8ToCRtDs89ZWAVlM/O48gDmw0M=,tag:+KDMeJSyQSJAHunCeOkrUw==,type:comment]
                - ENC[AES256_GCM,data:SgCoCmKG/axCfc6o/ZsBpz0E0Fde,iv:TdsX2QQJV61GAexRwyuQo2LzYk7r974OZ6TNrVSIgs4=,tag:ZNTtgvcvWiv7GT1tH5/uXA==,type:comment]
                - ENC[AES256_GCM,data:QhEJ+/CTdKiKvwz0xQ==,iv:C10W8R8wjYWvFcJpKo38SNVsSB6McjFeFk9bn4EwQ6s=,tag:8a2j/XojLfGtoL08C88WdQ==,type:comment]
                - ENC[AES256_GCM,data:nTd02j6U1M9IO9c=,iv:lFEBZacjDUtbDLTv1HGWQTYdNKB3i7XC+SUvqQvnEd8=,tag:LMpTNFwzeig3LLgjenKqYQ==,type:comment]
                - ENC[AES256_GCM,data:Cbm3Wkvk0NLXMyQXeg==,iv:edOMqsuIN0vKUCrBFhYnBEMhvKOyAy9SnA7hQVx1n08=,tag:gGiBM1pLbJ5YdqIHbhlEUw==,type:comment]
                - ENC[AES256_GCM,data:aul/tKMaJqdlkQ==,iv:ujyzic2jt0Uf7MLrbAzg7eeIKqiA97xIUNhoGprRHNU=,tag:TUIYtKWvGdK4626IFp7Qiw==,type:comment]
                - ENC[AES256_GCM,data:V3xKoLBSEdryUxJHWNvDs7yBg0disG9AGdluB+iA,iv:i7gNT4fMyugMqeCSbsSFGjRQdQQUsaOjhnnjUHHVqxM=,tag:sCko0pvwOQfhGG9Sd+6VHg==,type:comment]
                - ENC[AES256_GCM,data:NOqpZS8v0hp6zGwRgUhijTOHbVjXn/dUtLhQWOh0og==,iv:E2sq8xhU3+3I6apwhSeTC9umNXOLr1BVrJnSwPSKU48=,tag:KFBV3j4FNBxEjroPR6Ahng==,type:comment]
                - ENC[AES256_GCM,data:au2btSKmre0Q0aAqoBT27EwA2oevtZB52OVmjv0gjIDCe2syNj0+Jw==,iv:vcErQ2C6At9lspcDqm2ZzuQ2RRnNGGbFbjPKKwipazo=,tag:u4Ce95irhAinqemYkw3kcA==,type:comment]
                - ENC[AES256_GCM,data:UblUoy5mR2RFTPGp//ZXcYrMaA8i,iv:pKcmeZ1SOgiE3NQrL1To4wJ5ki0FF/9+FpvlykOtrwk=,tag:P+QBdZ9k1CTyazB8rlBZkA==,type:comment]
                - ENC[AES256_GCM,data:kIwbRoEvabsLyumVzk9DD6QzAlCMpWBGl54nMMJL+YQ161g8,iv:LtogJ2FuzVUQX7dTYGh0KF6jjik6BXCi8Aabn6VQRkY=,tag:4PeyFJrVFf/lDnI/WokeWw==,type:comment]
                - ENC[AES256_GCM,data:qg0N+Ds3C4nr+o7bugnxqA==,iv:h/wPLGyYrejrd/s/WoBg2U9kvgHQCu1Ct7ztquuAT4o=,tag:yvuFrIZM++uwK/aUzzMbow==,type:comment]
                - ENC[AES256_GCM,data:53WzpkGeEkNylVjkw9ACBZcJNJWsQoPodmApJZeSCRT2qb3Ra+DIs8AUwEuF,iv:iHLXlVlITNk8zwOJ8n5YxMZB7MHwQY+ielIGL3F+o9Q=,tag:LTrHZxzw8ZE9qPS6GER77g==,type:comment]
                - ENC[AES256_GCM,data:CKBCxVEdG2LAf5+CE6ImTUeXNQ==,iv:YD+JjGtybtHdNsFhIDtwwoOxqHIJDuNLH8l5anuwvb0=,tag:jcLb1gfVs3Oxhh1JfudeVw==,type:comment]
                - ENC[AES256_GCM,data:CQfVRfJykRvBxEZMdfmH0HI=,iv:1uoprNQmD92VHU4Md0bVrFCmjurXuHcxVTTmEyg5EqI=,tag:hdyeY3H7VtiMm9c9NCxD+Q==,type:comment]
                - ENC[AES256_GCM,data:BOjJPNBbZy/e5OV7HX5SxB4zpzU7Xw==,iv:CxVizEqTtb8verYKMqzmqntkpRT8tIcA4Pb3UGPEBic=,tag:kRLLfjHhTsHayB+KN7kbBg==,type:comment]
                - ENC[AES256_GCM,data:WDtCpOYlyzHPDCgR54leJeef+qXqNdibioQ=,iv:90kdG7G9Lok1SgfJ9bXGKCRUWBRElmnAXgyL3zGQNb4=,tag:bFu3Ei66a5DLZ4VZxVHcFw==,type:comment]
                - ENC[AES256_GCM,data:qppSzDemRViny5znkE1es+4=,iv:BS6vUnkwIcXaH90ZnN8YCOi/5J087/OtAFgj+VF0Xig=,tag:kjq2dDgqLYYgPy1jhXItfQ==,type:comment]
                - ENC[AES256_GCM,data:v16R3WbW1lMVZ8GMSJ292GrQZBKPVI35W/wAmhONHnNciF5tpYcbXlyZ19SSs/o=,iv:N2wy2MutypPOYiJ6qltj52gUPe3eZyRJ/V73WVuVxlQ=,tag:4NqW6PGCDfCuexsZfIkPhw==,type:comment]
                - ENC[AES256_GCM,data:cEWMZ3sV9+cVS2JLTgFssXxIZKA6ttwGgcH+H8xmZ529iddiYl+YkuWvsQ==,iv:zmJqpMu0Wr/J+ymkhrxlLocyHzhmZXUbFz1XkyrPv8Q=,tag:jcULHjeJVXHPM+ViZwHcVA==,type:comment]
                - ENC[AES256_GCM,data:MZ1onZZw22mK/Ym2EIlb9D6L2T2tgw==,iv:B3xGpmJYvYEawzNRvwkmkgeMnyaW2c68ZiZwSVuaLeg=,tag:RdfvmHJ5h8Aiayy73QwbJw==,type:comment]
                - ENC[AES256_GCM,data:5T8ppXfMGQOfcKiRjc7a9WjIMSn45aG3,iv:jlIzyk2l/2F3SjetS9USyQQHB3kVga/RDOUeQWTPPS8=,tag:N6napdoBW3MKY5si9AkL3Q==,type:comment]
                - ENC[AES256_GCM,data:zN/i7KWfXWanFmciTF23lVKsaA==,iv:oPSgYSLSqLOsLOCKlagLSvvRA7PtpoCbPuZsMOTnPfk=,tag:B34OS9KuVcvHJuxYvCm3Kg==,type:comment]
    staticClients:
    -   id: ENC[AES256_GCM,data:YMJ8a04=,iv:QcnBq7cVEjH5uDj8FF9XvQEXFP0p2DCWe0kb5PsgQQE=,tag:YQzg1opXOEzUY6xlZa0qHg==,type:str]
        redirectURIs:
        - ENC[AES256_GCM,data:JCu3HoGiisL+jR1VeCK15WJPpU7OXpgFRG2cyq/WulPUfVFmw+I1RIR7+1h1jA==,iv:g+m7nm+CnMnvCqcxrfrvActKR39bm/hv7hBiVBK8Uf4=,tag:KodqAnemJ8GmD2OTtCDuKA==,type:str]
        name: ENC[AES256_GCM,data:DFT6zwDdqklxvbglG+dDaa9Bt0Qw+g==,iv:aWNax2HMCH+CUYrchLdi+xqhqyLIp8hUEBOwOyBqo5w=,tag:YOYCrKI4CBucneD2XKz7OQ==,type:str]
        secret: ENC[AES256_GCM,data:4YfM9064gm3dNLBFAlVXd8hIACfnb4ex0FcdM+Tk,iv:yZ74v49datG8e48bb9pk4cY5lT60kYiNOhazLVJ73r0=,tag:+zcB6ofeNj/ErmU3xZhZug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-10-28T12:42:02Z'
        enc: WMDihj2ma9YSv-_6Yot4vXZ-zTWkH0wpaKruLZBt-t7hz85l6yLroV0Jj3iVzL_ORIZq35suYbhvstyraEqbeEM5a6QgywMbg4Vjc1QT5GFNqI8EJc1-XajEoUe3Xi-TFg1jratA_MS_TBCp8LPVCBAJDEJdFU1qjCdpVrXNS5XWuepLIxnj6z_VJprIe7qLMDaV_j9K-hqqyn-b7f4oDzOMQxOSrn25HJVWlP246G-zht0mP5-UYbd_W0JcEylH7gwa3Y7M46uwbIukoWmsX21MBqPpxHeUDLnzUSI7JNrRdU0VzLxPUxRHpBDiPU0pxbDG1zEDfp9cmEWiiea8-HwULGDe28hjFngCf6cj4R8O9nRO5KrINGOm3x2zOL8Md12JaHVN_L6hWAUjmh6_3NKtJz-aCYSyGzectWYVJV1w_e-F509kbPvOhLydH4xtddGQJ9PLQOGkI3wbbDwrXBUT3c76stDxnFJXAgRYJIXLTTX-9gesvyHuFDthc2j17s8SA-fpnpCPRi46_nSrnXiLM3VnhjYoRnIWHiDT181H6uUc93M9DuUS-BjjZe9viQnOhx8T45gbFD_XFjOFNLFscEKpPcjY-kpKcTKwjeaa8mnuCe21SZta3MMDpNF_pS5R4SyV4JvI0Qhz_lrk4QIfqTUwVGINGhnGjJKQHw4
    lastmodified: '2019-11-14T08:42:03Z'
    mac: ENC[AES256_GCM,data:8vtfYzPD6moHPdWfrNKB3DABNks90nGBGLHCe9Ieo8GoT0eC54NZiNd31czgmmH7g6g5TdsvqSfdmP7vAhqEaycBf1tEcR3pafK4gVySg4oE82Q/FbdG/I1/5mLmJAkApEJEatD8fdE8LWHvqZFshovRWqwSm1bponPdYH4jiMM=,iv:w6m8/YfWBC56ftW+3nrObBdjd5L/bbEOOaRQ6qwZJEw=,tag:qm9T+sBlgSi9lJj2G4jehQ==,type:str]
    pgp:
    -   created_at: '2019-10-28T12:42:02Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAaqDPHpcFO+jRmvIsRPU1j783lpyUYrfB2msLNgoWGtSI
            kLDAmAIAi2ld7rKtF3fzCTypZFlNpwOdkG+FBOAVLVLLbnUA4a1K0PyMlz+Yjvbm
            D/nXiYX6T3IyR1GOsDr+SAfWNAPr7EGRa+EESzboW58Hq6yxl1303hbwhogUqnVH
            wUCsjj68Dp1jlnHaEUHF3eLNCg2Ao1+9NIj+i5li4pz0GECBX+4zqQl9PbnD24BR
            ff5Wn7UG8qYV4YN5NNbNgBeT5CWJY6sNQHWhMXznl/5g860fRZ3tfgj39gtPHa05
            jhfoWa8OHvG1zVRvo/wqYvhzAclnx/I74tsUlvbzfyLskgKKFUpgiyVsAxC8WiUr
            H6Je4/JbeBBXWGVjbg2XRDDFPeNgnPQIf+rZv7X4zbZ9EMqbpFPrFQ5I9eUGsh2a
            N8B2jN3AURbHyoes9tfJlyvK3srGEokIoNkokDRxUYQyA26tLWpd/1GYSpJWNj0I
            PoWtP39tiLo/swzuPfWK0c4upzBwZMXAKxNrCXw/Dm5rChiLbla8imiR8qmfWVAA
            aoFgHiK54rj0TMedwynZHHFK7mWzHVve1yKJlxKwaxqziffdblIzm0LknjNVG9Nq
            s2iUzl8vYI1dxSGS2g5vt7fuiQgKRUVujoIEhJqOBEpbmx1ardDUVj0QUdQwtRjS
            4AHkccWUYVZhKNkM31qTYieeguH5heDj4ObhRRrg4OLV3Had4PjlWVVvLS90a6sO
            HNY+cweyUi2Gv3HyK5MH0JDQH3HzPq3gbOR2v16OQK/NQWqu4nQWOsLz4tb0htvh
            Z24A
            =BKLZ
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.4.0
