staticClients:
-   id: ENC[AES256_GCM,data:NLwPl2E=,iv:vljlbuBjxBTysdPSTp7jM8MRkEdwcFX6bJFBYtvGDRM=,tag:ptfIrWbx8gJynV0fP6oCwA==,type:str]
    redirectURIs:
    - ENC[AES256_GCM,data:rijx2G9Ye3nKLxE11LzQm7H0YaXH7KkB/63i89fr4aiAj6K3sQRKuqQ0SnD+WA==,iv:ncQfvl2vVZ+JxiUuEPeaVC/pGHze9CCkX68EwdE1aJE=,tag:+XtSVhg/0rTy6V95W5NkwQ==,type:str]
    name: ENC[AES256_GCM,data:1/G6wmGCWCXHnSDJxeQ38qwksut8aA==,iv:zlZ6sv6IHxd2VF+IhzwRinh1hN32evnIcz/qcrCWbI8=,tag:djNMsxbtw/BEGonYGrdPOQ==,type:str]
    secret: ENC[AES256_GCM,data:O5KPsbCPOVGkYrmPHJhCZmv7IzQmORCWGcmFCKyxwcY=,iv:iFhZpJMUQNrcvOvBEIkMMB+p3JhD8URPy8w6wrNwsD8=,tag:RMuNmyi+C3KfVcvzatRh+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-10-28T12:42:02Z'
        enc: WMDihj2ma9YSv-_6Yot4vXZ-zTWkH0wpaKruLZBt-t7hz85l6yLroV0Jj3iVzL_ORIZq35suYbhvstyraEqbeEM5a6QgywMbg4Vjc1QT5GFNqI8EJc1-XajEoUe3Xi-TFg1jratA_MS_TBCp8LPVCBAJDEJdFU1qjCdpVrXNS5XWuepLIxnj6z_VJprIe7qLMDaV_j9K-hqqyn-b7f4oDzOMQxOSrn25HJVWlP246G-zht0mP5-UYbd_W0JcEylH7gwa3Y7M46uwbIukoWmsX21MBqPpxHeUDLnzUSI7JNrRdU0VzLxPUxRHpBDiPU0pxbDG1zEDfp9cmEWiiea8-HwULGDe28hjFngCf6cj4R8O9nRO5KrINGOm3x2zOL8Md12JaHVN_L6hWAUjmh6_3NKtJz-aCYSyGzectWYVJV1w_e-F509kbPvOhLydH4xtddGQJ9PLQOGkI3wbbDwrXBUT3c76stDxnFJXAgRYJIXLTTX-9gesvyHuFDthc2j17s8SA-fpnpCPRi46_nSrnXiLM3VnhjYoRnIWHiDT181H6uUc93M9DuUS-BjjZe9viQnOhx8T45gbFD_XFjOFNLFscEKpPcjY-kpKcTKwjeaa8mnuCe21SZta3MMDpNF_pS5R4SyV4JvI0Qhz_lrk4QIfqTUwVGINGhnGjJKQHw4
    lastmodified: '2019-10-28T12:55:48Z'
    mac: ENC[AES256_GCM,data:3qjV1MO4Vt4+LWgXpYlAZmpWDsvWNFCxYs6L4qIsruABnTHDlppEjcHGuet3B2xHGNhWb7tWgMbzhzJOGN6RXPEB/lqhvahnOiDNTt1j+wui25yKgL1HoSsH7gwpqqLtFEXE+Hk9psGGbwiGoHKg7e3eiUmQegBTAGFReEr8Nhk=,iv:+d4yeu4qT47+fz7tzisCwEPATEX3HCGQSrETRUzbatE=,tag:MYhm8NLJo9AkoLjSuY1+EA==,type:str]
    pgp:
    -   created_at: '2019-10-28T12:42:02Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAaqDPHpcFO+jRmvIsRPU1j783lpyUYrfB2msLNgoWGtSI
            kLDAmAIAi2ld7rKtF3fzCTypZFlNpwOdkG+FBOAVLVLLbnUA4a1K0PyMlz+Yjvbm
            D/nXiYX6T3IyR1GOsDr+SAfWNAPr7EGRa+EESzboW58Hq6yxl1303hbwhogUqnVH
            wUCsjj68Dp1jlnHaEUHF3eLNCg2Ao1+9NIj+i5li4pz0GECBX+4zqQl9PbnD24BR
            ff5Wn7UG8qYV4YN5NNbNgBeT5CWJY6sNQHWhMXznl/5g860fRZ3tfgj39gtPHa05
            jhfoWa8OHvG1zVRvo/wqYvhzAclnx/I74tsUlvbzfyLskgKKFUpgiyVsAxC8WiUr
            H6Je4/JbeBBXWGVjbg2XRDDFPeNgnPQIf+rZv7X4zbZ9EMqbpFPrFQ5I9eUGsh2a
            N8B2jN3AURbHyoes9tfJlyvK3srGEokIoNkokDRxUYQyA26tLWpd/1GYSpJWNj0I
            PoWtP39tiLo/swzuPfWK0c4upzBwZMXAKxNrCXw/Dm5rChiLbla8imiR8qmfWVAA
            aoFgHiK54rj0TMedwynZHHFK7mWzHVve1yKJlxKwaxqziffdblIzm0LknjNVG9Nq
            s2iUzl8vYI1dxSGS2g5vt7fuiQgKRUVujoIEhJqOBEpbmx1ardDUVj0QUdQwtRjS
            4AHkccWUYVZhKNkM31qTYieeguH5heDj4ObhRRrg4OLV3Had4PjlWVVvLS90a6sO
            HNY+cweyUi2Gv3HyK5MH0JDQH3HzPq3gbOR2v16OQK/NQWqu4nQWOsLz4tb0htvh
            Z24A
            =BKLZ
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.4.0
