releases:
    - name: acme
      chart: ../charts/acme
      namespace: cert-manager
      wait: true
      timeout: 600
      force: true
      atomic: true
      values:
        - "../config/default/acme.yaml"
      secrets:
        - "../secrets/config/acme/secrets.yaml"
