releases:
    - name: cert-manager
      chart: stable/cert-manager
      namespace: cert-manager
      wait: true
      timeout: 600
      recreatePods: true
      force: true
      atomic: true

    - name: acme
      chart: ../charts/acme
      namespace: cert-manager
      wait: true
      timeout: 600
      force: true
      atomic: true
      values:
          - acme:
              email: "jenkins-infra@olblak.com"
