releases:
    - name: datadog
      namespace: datadog
      chart: stable/datadog
      version: 1.38.3
      wait: true
      timeout: 300
      atomic: true
      values:
        - "../config/default/datadog.yaml"
        - "../config/{{ .Values.cluster }}/datadog.yaml"
      secrets:
        - "../secrets/config/datadog/secrets.yaml"
