releases:
    - name: datadog
      namespace: datadog
      chart: stable/datadog
      version: 1.24.0
      wait: true
      timeout: 600
      recreatePods: true
      force: true
      atomic: true
      values:
        - "../config/datadog/values.yaml"
      secrets:
        - "../secrets/config/datadog/secrets.yaml"
