releases:
    - name: private-dex
      chart: stable/dex
      namespace: dex
      wait: true
      timeout: 300
      recreatePods: true
      force: true
      atomic: true
      values:
        - "../config/default/dex.yaml"
      secrets:
        - "../secrets/config/dex/secrets.yaml"
