helmDefaults:
  atomic: true
  force: true
  timeout: 600
  wait: true

releases:
    - name: default-release-jenkins
      chart: ../charts/jenkins
      namespace: release
      values:
        - "../config/default/jenkins-release.yaml"
      secrets:
        - "../secrets/config/release/jenkins/secrets.yaml"
      set:
        - name: namespace
          value: release

    - name: default-release-jenkins-env
      chart: ../charts/env-jenkins-release
      namespace: release
      force: true
      secrets:
        - "../secrets/config/release/env-jenkins/secrets.yaml"
