releases:
    - name: loki
      namespace: loki
      chart: loki/loki
      version: 0.14.1
      wait: true
      timeout: 100
      force: true
      atomic: true
      values:
        - "../config/default/loki.yaml"
    - name: promtail
      namespace: loki
      chart: loki/promtail
      version: 0.12.0
      wait: true
      timeout: 100
      force: true
      atomic: true
      values:
        - "../config/default/promtail.yaml"
