helmDefaults:
  atomic: true
  force: true
  timeout: 600
  wait: true

releases:
    - name: default-release-nexus
      chart: ../charts/nexus
      namespace: release
      values:
        - "../config/default/nexus.yaml"
      secrets:
        - "../secrets/config/release/nexus/secrets.yaml"
