helmDefaults:
  atomic: true
  force: true
  timeout: 600
  wait: true

releases:
    - name: polls
      chart: ../charts/polls
      namespace: polls
      secrets:
        - "../secrets/config/polls/secrets.yaml"
      values:
        - "../config/polls/values.yaml"
