releases:
    - name: reports
      namespace: reports
      chart: ../charts/reports
      wait: true
      timeout: 300
      force: true
      atomic: true
      values:
        - "../config/default/reports.yaml"
      secrets:
        - "../secrets/config/reports/secrets.yaml"
