releases:
    - name: wiki2md
      namespace: wiki2md
      chart: ../charts/wiki2md
      wait: true
      timeout: 300
      force: true
      atomic: true
      values:
        - "../config/wiki2md/values.yaml"
