ingress:
  enabled: true
  annotations:
    "certmanager.k8s.io/cluster-issuer": "letsencrypt-prod"
    "kubernetes.io/ingress.class": "public-ingress"
    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"

  hosts:
    - host: wiki2md.jenkins.io
      paths:
        - /

  tls:
    - secretName: wiki2md-tls
      hosts:
        - wiki2md.jenkins.io
