acme:
    dns01:
        azure:
            clientID: ENC[AES256_GCM,data:9tWKzGIwoG2NsNf2hLLwqtHRD+WIUNprRZhYElI8dkqOEwRG,iv:lCDO0FawbHiOTebWx6e28f0YndDVSDk67YdSsPiPqaQ=,tag:4d1BCc2TgI2ewpdhHb4WEw==,type:str]
            clientSecret: ENC[AES256_GCM,data:DmmMy7jphKdDRSJHNsrRFmdenq8=,iv:E5YsA67oD28dKzmLbB/+YLoWnYp+gnpntXVYZDJN2rc=,tag:5a3nfbA08bdsovDjnfnmrA==,type:str]
            subscriptionID: ENC[AES256_GCM,data:L3T9UeZ9o8etZBGXohAaZlTKSqH26ELWfbZthyEtxvXx1spz,iv:l3LWxsS/kmatDs2SueS4M0vDiCEdZntg/Iyf9DbLUh0=,tag:FvVqVEG260Si93sJPNNqVQ==,type:str]
            tenantID: ENC[AES256_GCM,data:4PPeBf+g/4NVSXspXwEKTNv/ptm6tHGvV2OB7ARbVqyDxXKn,iv:Buz03liyy2EBGcBMwFRRBBbNRpFxWNzeOMQ3npCSBNk=,tag:0//4qRnR88lTODAvAOZyrg==,type:str]
            resourceGroupName: ENC[AES256_GCM,data:QHwuESKvkrBmIu9rhnmcHSg=,iv:N/8I8KKuq5gotiI4lYDTw9QwDswI+vPZM1xoJW5nVdc=,tag:f4gSfXCDr7OM6OYNismEYg==,type:str]
            hostedZoneName: ENC[AES256_GCM,data:rZaTgYIGbu90pw==,iv:kGGLxc4HNYTaepJfIpm4ulpm7HlBqdARvtVMVFAtP68=,tag:qCVp9TE5x21QUH46zg41Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-06-14T12:59:10Z'
        enc: DVcA0vo1EGVDVZn2aVeJ0YHP7nzBStc1wNILw8DhjUOcEYfRd4G08pQODulWaj02Z0dGs8OS-SfFvvuj6eV_MjIjQJRgF80MD01tMsZMSu51DUUbu3r8e2tyCL7h8lK5rCZTklXV81cJmwO9fvdvYOxAxXlkr9YhkQ7ChOQngREW6Dv_UoScSoHcDI0UMjvCWWhu94xzI6Lz-kNMx0Szw7XoXVWmM9wgP0Tkv-CVMzZ9OxjuPwMFxkfc5rGAq6cvsnbGzAwHd4wPTBZRx34_8OM7gw38lQ1Cj6U1-v7LHJDBKZdjO3XCBKPz0l9wnZB0vxgUAGow0OwGKhLAxoTHNfnE54YBNtNcdI7oomNvpq9j2zBEiiJqG4IDwzStWu0UqfvF_ZxyMgrJk3yJIXdYF7kuUN92kzi73HsBvF8vb9Z7yEm8pq5JtiEWBJqjXHkHwOqYpYUjQAEhfmkedtu_2lsazPtTEwvFF6N_kBsuZ_YqyCp1QWmZK2QDtmi3MtYfLik2JV0sGF5HD3ys-d_q7oY1e5brb5eTEN1rAAHJV0EhsqBxqlQF8sxGKIAjq92p7AcosCY3_8sLVIPofF4h4TTpmgv61npJqDv31qX6y_sQzLFvjTU2LUPAK74ai1NgcxW3CNCJSC_6nYnazziufzppbSIeekyRYhoG7AjNDuA
    lastmodified: '2019-06-14T12:59:11Z'
    mac: ENC[AES256_GCM,data:VR3WUWZnhM6B8gm623Rt8CYQnclqWS1yGDHjwoZyqpsezVkS/+HP/KAYniC7Ct5gxO8yOwVuASkUnIdJ7fw0yhIindJvySK86xVjvZLLX+A6iRvQrnXrpTdz5PcKyx5yFvbNQkG4Abeu5LjoRWmaSgoItR47PYg4UhyYG9j9dt8=,iv:wHduCu7iJTTbW2i5t5s9mTl9YX9uJ+jiaViaWyQYXG8=,tag:gg2wh/DIi4JHDWKWEL4kjw==,type:str]
    pgp:
    -   created_at: '2019-04-19T07:38:34Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAVXVXX3dHb9xBoBUIPCxE9JF+WY903TvP8LwmJioj6/Wy
            40Cn1sI7dZNcg1fus7O+g6dZhNTmakMHze6mwCuAtu53N49ecUOdNeA9RFdkA0or
            rzp1rPffTsmNNa+vZfojoPK+ulRc6E9/PfNE4quaK7aXSHTSweFD7Yok3AOmZQW8
            t6eRTsi5hbZuNb55WJt3TWYudRmqZhy80jPuu+EKeVvCDu/38VaMZNOwaIxGDLe8
            pCunQPZ2vG6I9gte4pB6pyBic9cYsWAj8urlpiQ+rh1UsBQVDf3DERwAye6NsD5+
            bgsDC6nSScpCTEtn9FN/jl153bcFgZ31iEfn882+d5RqOjS1XrIdJzRdcGA9nmKM
            fFbiR4F2/zWFyHcldrnAVb5PyaBafTNinKoIlWWfVFBh4An98SxbTQkOzO1bgBIV
            gXct90frvoIe9O6lJsVa5Ev5vucyXtWjlpljboQ1ZKIjLT/NOw2HA2Pk+1LTGg3x
            5eMlo5jVWz5n4vZFh998H4FcEarqHf3QnvnG7IEHJWObEkt8zaCJVgKFBm9HPSOd
            J+lpODK6sS1qG5OWukjsJuZ8zCjyqE98vN+tNwVtba1zzqQ2KiBTBfcjWiNEjKj/
            54kbRaIYKM6VKDZAB0Wa9+xIkxfXPq623BTq8VE9ZTRxY9TJRIGzjWvqjuo+E+bS
            4AHkPCXLtG6jGaz33gaQ54y3V+GsO+Bs4BThBPTgmeJNN4154B7lLenuGcDnfqN2
            xB4yWBbOJXmTG7egc+gl2ySt6rNuZurgD+R/UWKmL0gjitF2TS0zOfnr4pQ1PVrh
            aQMA
            =XJX/
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.2.0
