acme:
    dns01:
        azure:
            clientID: ENC[AES256_GCM,data:ebXGqRify4nmE6qaRz+smkv/tzf7yCnJb9hWxiq6DGpWsiXh,iv:lCDO0FawbHiOTebWx6e28f0YndDVSDk67YdSsPiPqaQ=,tag:aoOy/qgS6mW42bHQDtu0Yg==,type:str]
            clientSecret: ENC[AES256_GCM,data:khpl7P97fOqkjL9WmLrDOaWXjIk=,iv:E5YsA67oD28dKzmLbB/+YLoWnYp+gnpntXVYZDJN2rc=,tag:TxKmUmj5sw7o/YAoOTUZ9Q==,type:str]
            subscriptionID: ENC[AES256_GCM,data:ur5iVLwlFDACW0ZJLTbsT7a6N18v1TS46Uov3UCuakuRH/QU,iv:l3LWxsS/kmatDs2SueS4M0vDiCEdZntg/Iyf9DbLUh0=,tag:dDgj+zsB8FCq4FYrMcOMCg==,type:str]
            tenantID: ENC[AES256_GCM,data:NcIpw/wB08nYJdGBvazT5qAcB7r7wIBQ6MMVT1cTeQ5ff8bF,iv:Buz03liyy2EBGcBMwFRRBBbNRpFxWNzeOMQ3npCSBNk=,tag:FAVJVva/0qZzSU9XGgsHPg==,type:str]
            resourceGroupName: ENC[AES256_GCM,data:q0OkJbTseMXTeaKHUQo4rmI=,iv:N/8I8KKuq5gotiI4lYDTw9QwDswI+vPZM1xoJW5nVdc=,tag:AGZ15X+GtoYvelbbxlXQ4Q==,type:str]
            hostedZoneName: ENC[AES256_GCM,data:xfSvQ1NOuRjPOw==,iv:kGGLxc4HNYTaepJfIpm4ulpm7HlBqdARvtVMVFAtP68=,tag:4lQoAIr8oi1JlUKFg97ZvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-04-19T09:25:36Z'
    mac: ENC[AES256_GCM,data:KJb2tjmkiSauMv72cmlFoxZp1M36Jpn4a2Ei+fyIgOnx1pQ0VK2oOUIR1GAy11Sopt58QrlHt6jFdgTQhJFUp64dSfQnDTXw0w742Ks0EFzP9aAgLCAaFvgJjwY/i75A8K7T7inq+ot8ZcLpu0joEYevm7gNz/7/dLrqVPsAJT8=,iv:k35GbpbB8Stgb0rRyyilRG29doHxrzPbtytnQkBCBYc=,tag:qmV1/9rpa9ugg/UFw2OArQ==,type:str]
    pgp:
    -   created_at: '2019-04-19T07:38:34Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAASN9lmzUQ3WHQwCZoxw4Km/UCuUtgi8uYzoT1K9jvrcLL
            IswdAm2oLJOL2xafjpfNJzbs2SQcsa+htSYfRbD7Z2ROmFpTu5rLJUo9uBymBOfv
            nkwiJeUV8fcKJ1f43F3bo2vcKQrJGdtQIyNo+8hwp674sJbML21suEF9u5rE3AyZ
            UlfvGzSKBugEz5vUiZd9Jx9rhXyF5vIHhQ4RsvGJRLJ25F4yCCSjNOIbbV5bHU90
            bzYHze5WKrQ8Z9mipGST/P4cwyR7A+lWbnPMJCSsh4jdgm+eAb9Y1Lv0jBx8UmAu
            gPNWHmgBMeGQGs+t/fUQoGKcp/8ZcB+SoweXECVtg4ugEciWGH4bQoO8ZY/suZSn
            dRAJmylsyovtHdI7QhhLS8Q5qzmSOc6XRFO3Z6QOrO2xf+7J6dGaGHND/8P2F/VA
            LQ/ys8lVGMjhNbKthBMilZn7tyFSW4/TLw+zTjqBcX2Xkl4l5slY8YNUXP7hI2Fm
            U0f9nuvFmNCCJjNUjsxqq8mMORuineNC348NAEUI54b6qmsXfkHm9sXjOm587Z7T
            sJtQB7ZIxxlC0RhH2hjimmllN3dA+UCIjTcYtlvKMO3KmR+cpNiPT0OBjWa4AapK
            AnkAHguqhlYUn0ZSrLruRVZNkCWdwj5gp6nsOtdExfDmCLCenXRg2XZ10hBTbDjS
            4AHkFRmbgA/8NMRjNbJ5tz8rHeG+N+D+4KLhWAvgjeKA74624B7lbNVnjwfM7MaV
            oRh9Z0z+spZL1KmcFfmVX2+zgBx0lJXgXuQCKfcNK/7YBL5SCzHe0igT4j4fJ2/h
            QgIA
            =22/o
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.2.0
